name: simple-ci
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pr4.py
  next_step:
    
    runs-on: ubuntu-latest
    needs: simple-test
    steps:
      - run: echo "Tests passed"
        if: ${{ always() && (hashFiles('res_pr4_test_et.txt') == hashFiles('res_pr4_test_et.txt') ) }}
      
