name: simple-ci
run-name: ${{ github.actor }} is doing GitHub Actions
on: [push]
jobs:
  simple-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: python3 pr4.py
        shell: sh
      - run: if cmp -s res_pr4_test.txt res_pr4_test_et.txt; 
          then echo "Test passed";
          else cat res_pr4_test.txt && echo !!!!!!!! && cat res_pr4_test_et.txt;
          fi
        shell: sh
      
